---
branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - master
  - main
  - next
  - next-major
  - name: dev
    prerelease: true
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
preset: conventionalcommits
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
